### ISSUE TITLE
help, error, I dont know what cause this.

### ISSUE THREAD

**Issue by alanding1989** [brooth/far.vim#72]
hello ,  thank you for creating such a nice plugin,  it reduce much of time to change symbols in multiple files. 
I have come with an error when I start far today, I dont know what happen and cant find the reseason.
I record a small **vedio**, pls help to solve the problem, thank you very much.
[error-vedio](https://asciinema.org/a/ef9sbhiBOSIXKuHjZhNg1vFYa)

```
error caught in async handler '/home/alanding/.cache/vimfiles-alan/repos/github.com/brooth/far.vim/rplugin/python3/far:function:_far_nvim_rpc_async_invoke [[['mod = importlib.import_module("far.sources.shell")', 'res = mod.search({"pattern": "vim_plugindir", "replace_with": "vim_plugin_config_dir", "range": [-1, -1], "limit": 1000, "file_mask": "**/*.vim", "cwd": "/home/alanding/.SpaceVim.d", "source": "rgnvim"}, {"cmd": ["rg", "--no-heading", "--column", "--no-messages", "--max-count={limit}", "--smart-case", "--ignore-case", "--glob={file_mask}", "{pattern}"], "fix_cnum": "next", "items_file_min": 30, "expand_cmdargs": 1},[])', 'self.nvim.command("call far#executors#nvim#callback("+str(res)+", 0)")']]]'
Traceback (most recent call last):
  File "/home/alanding/.cache/vimfiles-alan/repos/github.com/brooth/far.vim/rplugin/python3/far/__init__.py", line 31, in _far_nvim_rpc_invoke
    exec(execline)
  File "<string>", line 1, in <module>
  File "/home/alanding/software/anaconda3/envs/py36/lib/python3.6/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/alanding/software/anaconda3/envs/py36/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/alanding/software/anaconda3/envs/py36/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(call):E722: Missing comma in Dictionary: 
so \\\'.g:vim_plugindir.\\\'git-p.vim\\\'\', \'lnum\': 11, \'cnum\': 18},
{\'text\': "  exec \'so \'.g:vim_plugindir.\'defx-git.vim\'", \'lnum\': 16, \'cnum\': 16},
{\'text\': "  exec \'so \'.g:vim_plugindir.\'vim-gitgutter.vim\'", \'lnum\': 21, \'cnum\': 16}]}, 
{\'fname\': \'config/SpaceVim/plugins_before/tags.vim\', \'items\': [{\'text\': "exec \'so \'.g:vim_plugindir.\'vim-gutentags.vim\'", \'lnum\': 14, \'cnum\': 14}, 
{\'text\': "exec \'so \'.g:vim_plugindir.\'vista.vim\'", \'lnum\': 20, \'cnum\': 14}]}, 
{\'fname\': \'config/SpaceVim/plugins_before/langtools.vim\', \'items\': [{\'text\': "exec \'so \'.g:vim_plugindir.\'langtools.vim\'", \'lnum\': 6, \'cnum\': 14}]}, 
{\'fname\': \'config/SpaceVim/plugins_before/VersionControl.vim\', \'items\': [{\'text\': "exec \'so \'.g:vim_plugindir.\'vim-signify.vim\'", \'lnum\': 10, \'cnum\': 14}]}, 
{\'fname\': \'config/SpaceVim/plugins_before/leaderf.vim\', \'items\': [{\'text\': "exec \'so \'.g:vim_plugindir.\'LeaderF.vim\'", \'lnum\': 4, \'cnum\': 14}]}, 
{\'fname\': \'config/SpaceVim/plugins_before/autocomplete.vim\', \'items\': [{\'text\': "'
```

**Comment by brooth** [comment]
Plz attach the log file (see `:help`)

**Comment by dylan-chong** [comment]
I have found how to replicate it.

vimrc

```
let g:far#source = 'rgnvim'
let g:far#debug = 1
```

have this code:

```
"blooooo(0, 'ABC');"
```

Then `:Far blooooo bleh`

```
error caught in async handler '/Users/Dylan/.vim/plugged/far.vim/rplugin/python3/far:function:_far_nvim_rpc_async_invoke [[['mod = importlib.import_module("far.sources.shell")', 'res = mod.search({"case_sensitive": -1, "pattern": "blooooo", "replace_with": "bleh", "range": [-1, -1], "source": "rgnvim", "pattern_proc":
 "\\\\vblooooo", "limit": 1000, "file_mask": "/omitted", "cwd": "omitted", "word_boundary": 0, "regex": 1}, {"cmd": ["xargs", "rg", "--json", "--with-filename", "--no-heading", "--vimgrep", "--max-count
={limit}", "{pattern}", "{file_mask}"], "submatch": "all", "max_columns": 400, "items_file_min": 30, "expand_cmdargs": 1, "ignore_files": ["/Users/Dylan/.vim/plugged/far.vim/farignore"]},["--smart-case"])', 'self.nvim.command("call far#executors#nvim#callback("+str(res)+", 9)")']]]'
Traceback (most recent call last):
  File "/Users/Dylan/.vim/plugged/far.vim/rplugin/python3/far/__init__.py", line 31, in _far_nvim_rpc_invoke
    exec(execline)
  File "<string>", line 1, in <module>
  File "/Users/Dylan/Library/Python/3.8/lib/python/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/Dylan/Library/Python/3.8/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/Dylan/Library/Python/3.8/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(call):E722: Missing comma in Dictionary: ABC\');"', 'match': 'blooooo'}]}]}, 9)
```

removing the semicolon from the code no problem.

**Comment by thisisrandy** [comment]
The issue here is with single quotes. vimscript distinguishes between single- and double-quoted strings, whereas python does not. In the single-quoted case, single quotes within the string are escaped as `''`, whereas python escapes with a backslash. When the python dictionary is read back into vimscript, the difference in single quote escape sequence causes the error.

A somewhat crude solution to this is to bypass the portion of `shell.py` that decides whether to write the results to file based on how many there are and just always write to file. File writing uses python's `json.dump`, which means that we always get nice double-quoted strings that vimscript's `json_decode` can safely read.

I also tried using `json.dumps` to write `final_result['items']` and then reading back in via `json_decode` on the executor side, but that escapes backslashes before double quotes (`\\"`), which ends up causing the same issue. If someone knows of a way to avoid always writing to file, please ignore my PR and do that instead.
